### ISSUE TITLE
页面数量大于3的时候显示异常

### ISSUE THREAD

**Issue by coding0man** [xuejinwei/BottomNavigationViewDemo#1]
menu数量是4或者5的时候就异常了

**Comment by xuejinwei** [comment]
BottomNavigationViewDemo，在四个或者五个时候显示方式的确是和三个不一样的，详情看 material design 官方文档：https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-specs

**Comment by coding0man** [comment]
已解决
